sudo: false
language: go
go:
  - 1.7.x
  - 1.8.x
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - go get github.com/Stalis/Distorted-Ascension/DEEngine
branches:
  only:
    - master
    - develop
    - /^release-.*$/
