// Code generated by "stringer -type=tCellType"; DO NOT EDIT.

package Map

import "fmt"

const _tCellType_name = "CELL_LAND_1CELL_LAND_2CELL_LAND_3"

var _tCellType_index = [...]uint8{0, 11, 22, 33}

func (i tCellType) String() string {
	if i < 0 || i >= tCellType(len(_tCellType_index)-1) {
		return fmt.Sprintf("tCellType(%d)", i)
	}
	return _tCellType_name[_tCellType_index[i]:_tCellType_index[i+1]]
}
